ユーザとホスト名を確認

diff --git a/tobas_dev_tools/scripts/tobas_build_release b/tobas_dev_tools/scripts/tobas_build_release
--- a/tobas_dev_tools/scripts/tobas_build_release
+++ b/tobas_dev_tools/scripts/tobas_build_release
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Check user and host
+if [ "$(id -un)" != "pi" ] || [ "$(hostname -s)" != "tobas" ]; then
+  echo "This script can only be executed on RPi." >&2
+  exit 1
+fi
+
 # Set paths
 COLCON_WS=~/colcon_ws
 RELEASE_DIR=${COLCON_WS}/release
@@ -19,7 +25,7 @@ export MAKEFLAGS="-j1"
 # XXX: The "-march=native" option has little impact on speeding up performance on ARM CPUs.
 colcon build --merge-install --parallel-workers 1 --install-base ${INSTALL_BASE} --build-base ${BUILD_BASE} --cmake-args -DCMAKE_BUILD_TYPE=Release $1 $2
 if [ $? -ne 0 ]; then
-  echo "Failed to build."
+  echo "Failed to build." >&2
   exit 1
 fi
 
diff --git a/tobas_dev_tools/scripts/tobas_clean b/tobas_dev_tools/scripts/tobas_clean
--- a/tobas_dev_tools/scripts/tobas_clean
+++ b/tobas_dev_tools/scripts/tobas_clean
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Check user and host
+if [ "$(id -un)" != "pi" ] || [ "$(hostname -s)" != "tobas" ]; then
+  echo "This script can only be executed on RPi." >&2
+  exit 1
+fi
+
 # Remove unnecessary files
 sudo rm -rf /tmp/*
 sudo rm -rf /var/tmp/*
@@ -27,7 +33,7 @@ sudo rm -rf ./src/*
 # Clear network settings
 sudo sed -i '4,$ d' /etc/wpa_supplicant/wpa_supplicant.conf
 if [ $? -ne 0 ]; then
-  echo "Failed to edit /etc/wpa_supplicant/wpa_supplicant.conf."
+  echo "Failed to edit /etc/wpa_supplicant/wpa_supplicant.conf." >&2
   exit 1
 fi
 
diff --git a/tobas_dev_tools/scripts/tobas_deploy_upto b/tobas_dev_tools/scripts/tobas_deploy_upto
--- a/tobas_dev_tools/scripts/tobas_deploy_upto
+++ b/tobas_dev_tools/scripts/tobas_deploy_upto
@@ -6,7 +6,7 @@ PARDIR=$(realpath $(dirname "$0"))
 echo "Stopping Tobas main service."
 sudo systemctl stop tobas_real.target
 if [ $? -ne 0 ]; then
-  echo "Failed to stop tobas_real.target."
+  echo "Failed to stop tobas_real.target." >&2
   exit 1
 fi
 
@@ -14,7 +14,7 @@ fi
 echo "Building Tobas."
 bash ${PARDIR}/tobas_build_release_upto $1
 if [ $? -ne 0 ]; then
-  echo "Failed to build."
+  echo "Failed to build." >&2
   exit 1
 fi
 
@@ -22,7 +22,7 @@ fi
 echo "Installing Tobas."
 bash ${PARDIR}/tobas_install
 if [ $? -ne 0 ]; then
-  echo "Failed to install."
+  echo "Failed to install." >&2
   exit 1
 fi
 
@@ -30,7 +30,7 @@ fi
 echo "Restarting Tobas main service."
 sudo systemctl restart tobas_real.target
 if [ $? -ne 0 ]; then
-  echo "Failed to restart tobas_real.target."
+  echo "Failed to restart tobas_real.target." >&2
   exit 1
 fi
 
diff --git a/tobas_dev_tools/scripts/tobas_install b/tobas_dev_tools/scripts/tobas_install
--- a/tobas_dev_tools/scripts/tobas_install
+++ b/tobas_dev_tools/scripts/tobas_install
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Check user and host
+if [ "$(id -un)" != "pi" ] || [ "$(hostname -s)" != "tobas" ]; then
+  echo "This script can only be executed on RPi." >&2
+  exit 1
+fi
+
 # Set paths
 COLCON_WS=~/colcon_ws
 RELEASE_DIR=${COLCON_WS}/release
@@ -8,7 +14,7 @@ INSTALL_BASE=${RELEASE_DIR}/install
 sudo rm -rf /opt/tobas # 一旦削除しないとsourceが反映されないことがあった
 sudo cp -r ${INSTALL_BASE} /opt/tobas
 if [ $? -ne 0 ]; then
-  echo "Failed to copy ${INSTALL_BASE} to /opt/tobas."
+  echo "Failed to copy ${INSTALL_BASE} to /opt/tobas." >&2
   exit 1
 fi
 
diff --git a/tobas_dev_tools/scripts/tobas_sync b/tobas_dev_tools/scripts/tobas_sync
--- a/tobas_dev_tools/scripts/tobas_sync
+++ b/tobas_dev_tools/scripts/tobas_sync
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Check user and host
+if [ "$(id -un)" = "pi" ] && [ "$(hostname -s)" = "tobas" ]; then
+  echo "This script cannot be executed on RPi." >&2
+  exit 1
+fi
+
 # Tobasリポジトリの親ディレクトリに移動
 cd $(realpath $(dirname "$0"))/../../../
 
