edit: tobas_deploy_upto

diff --git a/tobas_dev_tools/scripts/tobas_deploy_upto b/tobas_dev_tools/scripts/tobas_deploy_upto
--- a/tobas_dev_tools/scripts/tobas_deploy_upto
+++ b/tobas_dev_tools/scripts/tobas_deploy_upto
@@ -3,6 +3,13 @@
 export COLCON_WS=~/colcon_ws
 PARDIR=$(realpath $(dirname "$0"))
 
+# Stop main service
+sudo systemctl stop tobas_real.service
+if [ $? -ne 0 ]; then
+  echo "Failed to stop tobas_real.service."
+  exit 1
+fi
+
 # Update repositories
 cd ${COLCON_WS}
 vcs pull
@@ -22,6 +29,13 @@ fi
 bash ${PARDIR}/tobas_install
 if [ $? -ne 0 ]; then
   echo "Failed to install."
+  exit 1
+fi
+
+# Restart main service
+sudo systemctl restart tobas_real.service
+if [ $? -ne 0 ]; then
+  echo "Failed to restart tobas_real.service."
   exit 1
 fi
 
