edit: tobas_install

diff --git a/tobas_dev_tools/scripts/tobas_install b/tobas_dev_tools/scripts/tobas_install
--- a/tobas_dev_tools/scripts/tobas_install
+++ b/tobas_dev_tools/scripts/tobas_install
@@ -6,3 +6,9 @@ export RELEASE_DIR=${COLCON_WS}/release
 export INSTALL_BASE=${RELEASE_DIR}/install
 
 sudo cp -r ${INSTALL_BASE} /opt/tobas
+if [ $? -ne 0 ]; then
+  echo "Failed to copy ${INSTALL_BASE} to /opt/tobas."
+  exit 1
+fi
+
+echo -e "\033[32mInstallation finished successfully.\033[0m"
